package io.github.rowak.nanoleafdesktop.shortcuts;

public enum ActionType
{
	DEVICE_ON, DEVICE_OFF, DEVICE_TOGGLE,
	INCREASE_BRIGHTNESS, DECREASE_BRIGHTNESS, SET_BRIGHTNESS,
	INCREASE_COLOR_TEMP, DECREASE_COLOR_TEMP, SET_COLOR_TEMP,
	SET_EFFECT, NEXT_EFFECT, PREVIOUS_EFFECT,
	SET_HUE, SET_SATURATION,
	SET_RED, SET_GREEN, SET_BLUE
}
