package io.github.rowak.nanoleafdesktop.shortcuts;

public enum ActionType
{
	DEVICE_ON, DEVICE_OFF, DEVICE_TOGGLE,
	INCREASE_BRIGHTNESS, DECREASE_BRIGHTNESS,
	INCREASE_COLOR_TEMP, DECREASE_COLOR_TEMP,
	SET_EFFECT, SET_BRIGHTNESS, SET_COLOR_TEMP
}
